dataset:
  name: TropicalLeafWood
  dataset_path: ../data/leaf_wood/
  train_dir: train
  val_dir: val
  test_dir: test
  test_result_folder: test_pred_kpconv
  cache_dir: ./logs/cache
  use_cache: true
  class_weights: [34512040, 9127323]
  ignored_label_inds: []
model:
  name: KPConv
  ckpt_path: ./logs/CustomKPConv_TropicalLeafWood_torch/checkpoint_2023-11-27_22:21:17/ckpt_best.pth 
  is_resume: false
  augment_noise: 0.00 # 0.001
  augment_rotation: #vertical
  augment_scale_anisotropic: true
  augment_scale_max: 1. # 1.1
  augment_scale_min: 1. # 0.9
  augment_symmetries:
  - false # true
  - false
  - false
  augment:
    recenter:
      dim: [0, 1, 2]
    rotate:
      method: vertical
    scale:
      min_s: 0.9 # 0.95
      max_s: 1.1 # 1.05
    noise:
      noise_std: 0.001
  batcher: ConcatBatcher
  first_subsampling_dl: 0.02
  ignored_label_inds: []
  in_features_dim: 3
  in_points_dim: 3
  lbl_values: [0, 1]
  min_in_points: 10000 # 65536
  num_classes: 2
pipeline:
  name: SemanticSegmentation
  # device: 'cuda:0'
  num_workers: 0
  pin_memory: false
  optimizer:
    lr: 0.001
  scheduler_gamma: 0.9886
  batch_size: 1
  test_batch_size: 1
  val_batch_size: 1
  max_epoch: 100
  save_ckpt_freq:  
  save_ckpt_best: True
  main_log_dir: ./logs
  train_sum_dir: train_log
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
