dataset:
  name: TropicalLeafWood
  dataset_path: /mnt/c/Users/wavdnbro/OneDrive - UGent/Documents/spacetwin/datasets/trees_kim  # ../data/leaf_wood # /mnt/c/Users/wavdnbro/OneDrive - UGent/Documents/spacetwin/datasets/leafon_individual_TLSdata # 
  train_dir: train
  val_dir: val
  test_dir: test
  # file_name: rc_172_pc.npy # Single file for prediction
  test_result_folder: test_pred
  cache_dir: ./logs/cache_pointTransformer
  use_cache: true
  class_weights: [34512040, 9127323]
  ignored_label_inds: []
model:
  name: PointTransformer
  batcher: ConcatBatcher
  ckpt_path: ./logs/CustomPointTransformer_TropicalLeafWood_torch/checkpoint/ckpt_best_pointtransformer.pth # path/to/your/checkpoint
  # is_resume: False
  in_channels: 3
  blocks: [2, 3, 4, 6, 3]
  num_classes: 2
  voxel_size: 0.02
  max_voxels: 65536 # = num_points in randlanet config
  ignored_label_inds: []
  augment:
    recenter:
      dim: [0, 1, 2]
    rotate:
      method: vertical
    scale:
      min_s: 0.9 # 0.95
      max_s: 1.1 # 1.05
    noise:
      noise_std: 0.001
pipeline:
  name: SemanticSegmentation
  device: 'cuda:0'
  num_workers: 8
  pin_memory: True
  optimizer:
    lr: 0.001 # 0.02
  max_epoch: 100
  scheduler_gamma: 0.9886 # 0.99
  batch_size: 3 # this one is also used for inference
  test_batch_size: 2
  val_batch_size: 2
  main_log_dir: logs
  save_ckpt_freq: # Saves weights every x epochs + at the last epoch
  save_ckpt_best: True # Saves only best model weights based on validation score 
  train_sum_dir: train_log
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1