services:
  open3dml:
    build: .
    image: open3dml
    container_name: open3dml
    working_dir: /project
    volumes:
      - ../cfg:/project/cfg
      - ../logs:/project/logs
      - ../scripts:/project/scripts
      - ../train_log:/project/train_log
      - ../data:/project/data # Potentially change '../data' to your own data path
    stdin_open: true 
    tty: true
    ipc: host 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
